Pip/python upgrade
lappis-unb/rasa-ptbr-boilerplate pull request #203
Opened 2021-04-03 16:23 UTC by staticdev

## Descrição

Atualização das versões 3.6 e 3.7 do Python para 3.8 (novas versões do rasa funcionam melhor no 3.8). Essas imagens vem com a nova versão do pip que não terá problemas com o resolver novo.

## Resolve (Issues)

Closes #202

2021-04-21 11:54 UTC, BrunaNayara commented
@arthurTemporim pode rodar e ver se tá tudo ok?

2021-04-22 02:10 UTC, arthurTemporim commented
Essa contribuição realmente é muito boa! atualiza bem como utilizamos os pacotes PIP 🚀 

Mas eu testei ela clonando sua branch e não funcionou tanto usando um virtualenv quanto em docker, segue os logs:

Virtualenv: Python 3.8.8 pip 21.0.1
```
INFO: pip is looking at multiple versions of httptools to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of aiofiles to determine which version is compatible with other requirements. This could take a while.
Collecting aiofiles>=0.3.0
  Downloading aiofiles-0.5.0-py3-none-any.whl (11 kB)
  Downloading aiofiles-0.4.0-py3-none-any.whl (9.2 kB)
  Downloading aiofiles-0.3.2-py3-none-any.whl (9.9 kB)
  Downloading aiofiles-0.3.1-py3-none-any.whl (9.2 kB)
  Downloading aiofiles-0.3.0-py3-none-any.whl (9.2 kB)
INFO: pip is looking at multiple versions of h11 to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
```

Docker (com o comando `make first run`):
```
Collecting sniffio
  Downloading sniffio-1.1.0-py3-none-any.whl (4.5 kB)
  Downloading sniffio-1.0.0-py3-none-any.whl (4.4 kB)
INFO: pip is looking at multiple versions of aiofiles to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of httpcore to determine which version is compatible with other requirements. This could take a while.
Collecting httpcore==0.11.*
  Downloading httpcore-0.11.0-py3-none-any.whl (52 kB)

```

A build só passou no `github actions` pois adicinei o comando pra configuração `--use-deprecated=legacy-resolver` do PIP no arquivo [Nessa linha](https://github.com/lappis-unb/rasa-ptbr-boilerplate/blob/81dab2d7314005d4dc62ed43544625e5830c7f88/.github/workflows/build.yml#L31).
@staticdev Esta configuração funcinou em seu ambiente? Tem alguma configuração a mais pra ser feita?
Esse é meu SO: `Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux`

2021-04-22 02:13 UTC, arthurTemporim requested changes

2021-04-22 02:13 UTC, arthurTemporim commented on .github/workflows/build.yml
> +        python-version: [3.8, 3.7]
```suggestion
        python-version: [3.7, 3.8]
```

2021-04-22 02:13 UTC, arthurTemporim commented on bot/Makefile
> -# TODO: This is a hotfix while RASA don't solve dependencies issues.
Esta remoção não resolve o problema de instalação do pip

2021-04-22 02:13 UTC, arthurTemporim commented on docker/consumer.Dockerfile
> +FROM python:3.8.9-slim-buster
Boa atualização, utilizar a ultima versão do debian na imagem do docker é melhor mesmo

2021-04-23 16:03 UTC, staticdev commented
@arthurTemporim testei local aqui no Ubuntu 20.10 e funcionou legal. Mas acabei de quebrar meu ambiente por causa do ROCm (pra rodar modelos com GPU da AMD). Vou tentar ver o que pode ser.. as vezes faltou comitar alguma coisa..

2021-05-18 13:29 UTC, mpomarole commented
Seria muito legal alguém testar essa mudança no macOS e com um laptop com o chip M1.
Estou tendo alguns problemas com docker + tensorflow agora que estou com um laptop M1. Quando rodo `make build`, ele dá um problema na versão do tensorflow e python. Quando resolver, mando um PR.

2021-05-18 13:39 UTC, arthurTemporim commented
@mpomarole Você poderia, por favor, colocar os logs desse erro? Não tenho acesso a um MAC M1 no momento. Vai ajudar bastante pra corrigir esse problema :D

2021-05-18 13:59 UTC, mpomarole commented
> @mpomarole Você poderia, por favor, colocar os logs desse erro? Não tenho acesso a um MAC M1 no momento. Vai ajudar bastante pra corrigir esse problema :D

@arthurTemporim acredito que hoje eu consiga descobrir o que está acontecendo, mas aqui está

```
#10 57.81 ERROR: Could not find a version that satisfies the requirement tensorflow-addons<=0.12,>=0.10 (from rasa==2.5.0->-r requirements.txt (line 1)) (from versions: none)
#10 57.81 ERROR: No matching distribution found for tensorflow-addons<=0.12,>=0.10 (from rasa==2.5.0->-r requirements.txt (line 1))
#10 57.89 make: Leaving directory '/tmp'
#10 57.89 make: *** [Makefile:14: install] Error 1
------
executor failed running [/bin/sh -c apt-get update                                                             &&     apt-get install -y gcc make build-essential git                            &&     make  -C /tmp install                                                      &&     python -c "import nltk; nltk.download(['stopwords', 'rslp', 'punkt']);"    &&     find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf               &&     apt-get clean                                                              &&     apt-get remove -y build-essential]: exit code: 2
```

2021-05-21 12:16 UTC, mpomarole commented
Rasa won't run/install on Apple M1 chip machines because of a tensorflow dependency. See [this thread](https://forum.rasa.com/t/apple-m1-illegal-hardware-instruction-using-any-rasa-command/37946/23).

2021-05-22 07:24 UTC, staticdev commented
@mpomarole isso é esperado. O M1 é um arm, o rasa ainda não tem suporte (acho que o tensorflow se vc forçar um pouco até roda, alguns colegas já comentaram comigo).

2021-05-25 08:42 UTC, mpomarole commented
> @mpomarole isso é esperado. O M1 é um arm, o rasa ainda não tem suporte (acho que o tensorflow se vc forçar um pouco até roda, alguns colegas já comentaram comigo).

É, bem infelizmente não têm suporte. Estou tendo que alugar uma ec2 aws instance para poder fazer experimentos com rasa.

2021-06-16 03:23 UTC, arthurTemporim commented
@staticdev vou fechar este PR pois as atualizações aqui propostas já foram inseridas nos PRs #206 e #208 .
Muito obrigado pela iniciativa e pela criação do PR 🥇

2021-06-16 03:23 UTC, closed without merging